create schema IF NOT EXISTS basico;
create schema IF NOT EXISTS facturacion;
create schema IF NOT EXISTS inventario;
create schema IF NOT EXISTS public;
create schema IF NOT EXISTS auditoria ;
create schema IF NOT EXISTS compras ;
create schema IF NOT EXISTS nomina ;
create schema IF NOT EXISTS contabilidad;
create schema IF NOT EXISTS bancos;
create schema IF NOT EXISTS caja;
create schema IF NOT EXISTS seguridad;
